import NavigationBar from '../components/NavigationBar'
import './globals.css'

export const metadata = {
  title: 'My first Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://bootswatch.com/5/flatly/bootstrap.min.css" />
      </head>
      <body>
        <NavigationBar/>
        <div className="container">{children}</div>
      </body>
    </html>
  )
}
